apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: ${artifactId}-ingress-grpc
spec:
  rules:
     - host: custos.scigap.org
       http:
        paths:
          - path: /org.apache.custos.sharing.management.service.SharingManagementService(/|$)(.*)
            backend:
              serviceName: sharing-management-service
              servicePort: grpc

  tls:
    - hosts:
        - custos.scigap.org
      secretName: tls-secret