apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /identity-management/$2
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: custos.scigap.org
      http:
        paths:
          - path: /identity-management(/|$)(.*)
            backend:
              serviceName: identity-management-service
              servicePort: envoyhttp

  tls:
    - hosts:
        - custos.scigap.org
      secretName: tls-secret